### ISSUE TITLE
Support lts-15/ghc-8.*

### ISSUE THREAD

**Issue by googleson78** [Holmusk/elm-street#101]
It seems to work fine when I try to use lts-15.4. So I guess the only thing required is to remove/bump upper bounds?

I'm not sure what your policy is on this, so I didn't do a pr straight up.

**Comment by turboMaCk** [comment]
resolved in https://github.com/Holmusk/elm-street/pull/103

**Comment by turboMaCk** [comment]
@arbus I think this issue can be closed now.
