### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by ChShersh** [Holmusk/elm-street#12]
If we're going to use Circle CI then it's probably to use `fpco` Docker image with chosen LTS. But I don't know how to test on multiple GHC versions with both `cabal` and `stack` using Circle CI and Docker...

If we're going to use Travis CI, then @vrom911 and I already have example of CI configuration with matrix for multiple GHC versions for both `cabal` and `stack`.

**Comment by arbus** [comment]
Happy to stick to Travis CI, setting up CIs is not real work just a chore. As long as it works, I'm ok with anything

**Comment by ChShersh** [comment]
@arbus Could you please enable Travis CI integration for this repository? We will insert `.travis.yml` file with the configuration in this repository. But first we need to enable Travis. Somehow I can't do this...

**Comment by arbus** [comment]
You are now an admin on the org, go forth and prosper
