### ISSUE TITLE
Translate haskell string type to elm string type instead of List Char

### ISSUE THREAD

**Issue by HugoPeters1024** [Holmusk/elm-street#122]
Due to the helpful derivation of `Elm a => Elm [a]`, the String datatype will have an Elm definition of `List Char` which is not desirable in almost all cases. Is there a way to make an overlapping typeclass instance that will handle this edge case?

**Comment by jhrcek** [comment]
I agree, I already stumbled upon this annoying behavior multiple times.
Let me see if I can change it without breaking too many things.

**Comment by jhrcek** [comment]
I published 0.2.0.0 version of this package containing the fix to hackage.
https://hackage.haskell.org/package/elm-street-0.2.0.0
