### ISSUE TITLE
Type aliases get generated with their rhs leading to duplicate definitions

### ISSUE THREAD

**Issue by HugoPeters1024** [Holmusk/elm-street#124]
The following haskell snippet:

```haskell
data CoreId = CoreId { name :: Text
                     , bindId :: Int 
                     }
                     deriving (Show, Generic)
                     deriving (Elm, ToJSON, FromJSON) via ElmStreet CoreId

type CoreBndr = CoreId
```

leads to the following generated Elm types:

```elm
type alias CoreId =
    { name : String
    , id : Int
    }

type alias CoreId =
    { name : String
    , id : Int
    }
```

I suspect that the type alias name is fetched from the rhs instead of the lhs. Perhaps more ideally it gets generated as an actual type alias. 

P.S.

I'm loving the library thusfar and its proving very useful, thanks for your hard work

**Comment by jhrcek** [comment]
I assume that your goal was to generate elm code like this:

```elm
type alias CoreId =
    { name : String
    , id : Int
    }

type alias CoreBndr =
    CoreId
```

From haskell code like this:

```haskell
-- your example definitions...

type Types = '[CoreId, CoreBndr]

main :: IO ()
main = generateElm @Types $ defaultSettings "frontend/src" ["Core", "Generated"]
```


I would say this behavior is as expected.

According to section 4.2.2 in [Haskell 98 report]( https://www.haskell.org/onlinereport/decls.html)
"Type synonyms are a convenient, but strictly syntactic, mechanism to make type signatures more readable."

So CoreBndr is really just another name for CoreId. Importantly it has identical instance of Elm type class => the same code is generated for it. If you wanted different code to be generated, you would need CoreBndr to have different instance of Elm type class. But AFAIK there's no way to associate different type class with type alias.

**Comment by HugoPeters1024** [comment]
Thanks for the explanation, for now I've settled to work without the extra clarity of the alias
