### ISSUE TITLE
Allow for customisation of the field names that are generated

### ISSUE THREAD

**Issue by silky** [Holmusk/elm-street#129]
Following a conversation in https://github.com/Holmusk/elm-street/pull/20 it would be convenient to be able to customise the field-name-generation rules when emitting elm code.

In particular, the main culprit is the places this function - https://github.com/Holmusk/elm-street/blob/master/src/Elm/Generic.hs#L291- is used.

If that function could instead live in the `Settings` - https://hackage.haskell.org/package/elm-street-0.2.0.0/docs/Elm-Generate.html#t:Settings - then we'd get to customise that :)

**Comment by jhrcek** [comment]
Having the function in Settings is probably not a good idea, because settings are meant to be shared across multiple types potentially. We'd have to make this configurable on per-type basis.

**Comment by turboMaCk** [comment]
just a note from my side: I think with new record dot syntax this issue will become only more relevant since a need for current implicit prefix striping will become less relevant.

Also I second @jhrcek's opinion on allowing configuration on per type bases. That IMO at least should be the underlying philosophy.

**Comment by silky** [comment]
it's a hack, but to avoid extreme configuration doom, note that the function already depends on _the type name_, so you could always check that as a string

**Comment by silky** [comment]
( fwiw, for my use case i'm happy with a change for all types )

**Comment by jhrcek** [comment]
@silky please check and let us know if this change is sufficient for your purposes
https://github.com/Holmusk/elm-street/pull/131

I wanted to keep the old behavior (stripping type name prefix) so as not to break dozens of instances our codebase at work uses. Yet to provide way to override that default behavior in a way that is not too hacky or inconvenient.

This screenshot from updated haddock tells you how you could use the new capability:

![Screenshot from 2023-03-25 09-41-47](https://user-images.githubusercontent.com/2716069/227706988-195831c9-f7f8-49ef-ba0c-5f43b15065b0.png)

**Comment by jhrcek** [comment]
The abovementioned PR was merged and released as part of 0.2.1.1 release.
See https://hackage.haskell.org/package/elm-street-0.2.1.1/docs/Elm-Generic.html#t:CodeGenOptions for example of how to use it
