### ISSUE TITLE
Missing test/golden/oneType.json on hackage

### ISSUE THREAD

**Issue by alaendle** [Holmusk/elm-street#135]
Hackage distribution misses file - see https://hackage.haskell.org/package/elm-street-0.2.1.0/src/.
```
Registering library 'types' for elm-street-0.2.1.0..
elm-street                 > test (suite: elm-street-test)
                          
Progress 64/65: elm-street
golden tests
  Default CodeGenOptions
    Golden JSON -> Haskell == default [✘]
    default -> JSON -> Haskell == default [✔]
  Custom CodeGenOptions
    should decode type with custom CodeGenOptions [✔]
    should encode type with custom CodeGen [✔]

Failures:

  test/Test/Golden.hs:13:9: 
  1) golden tests, Default CodeGenOptions, Golden JSON -> Haskell == default
       uncaught exception: IOException of type NoSuchThing
       test/golden/oneType.json: openBinaryFile: does not exist (No such file or directory)
```

**Comment by jhrcek** [comment]
Thanks for reporting this @alaendle 
I wonder how you noticed this and reported it so quickly.
Are you some kind of hackage trustee or where did you notice this error? Just curious :smile:

**Comment by alaendle** [comment]
Very close, stackage curator - so trying to build and re-enable all kind of packages in my spare time 🤯

**Comment by turboMaCk** [comment]
I would recommend we run tests from installation rather than source code directory (which is what hides this issue). This would help to uncover all the files that tests depend on but are missing in the distribution. I don't know exactly how to do this with stack though since I usually test things like this using nix in my projects. But I think it should not be that complicated. You can test it even yourself on your machine by running tests for the library using cabal with `cabal install --run-tests elm-street` or something like that.

**Comment by jhrcek** [comment]
I'll look into that later.
In the meantime I uploaded https://hackage.haskell.org/package/elm-street-0.2.1.1 which should have the missing file

**Comment by jhrcek** [comment]
Resolved in https://github.com/Holmusk/elm-street/pull/136

**Comment by alaendle** [comment]
> I'm curious about the process. Where did you see the failure? What made you look at exactly this package? Just looking for pointers about what I could potentially do to prevent these kinds of "problematic" releases 😄 I'm gonna push a fixed version to hackage later today.

Well I just took a look at this package because it was disabled in stackage nightly and a new release appeared on hackage - so I just used https://github.com/commercialhaskell/stackage/blob/master/verify-package to verify if there is still a problem with this package, or if I could re-include it to stackage nightly.

Long story short, `elm-street` should reappear in one of the next nightly stackage builds.
