### ISSUE TITLE
Scaffold some minimal elm project for tests

### ISSUE THREAD

**Issue by ChShersh** [Holmusk/elm-street#33]
So we can put all types in some local directory, generate elm code very fast and check whether it compiles (in order to fix all errors).

**Comment by ChShersh** [comment]
I think it should be enough to test only the following data types:

```haskell
data Prims = Prims
    { primsUnit :: ()
    , primsBool :: Bool
    , primsChar :: Char
    , primsInt :: Int
    , primsFloat :: Double
    , primsString :: String
    , primsMaybe :: Maybe Word
    , primsResult :: Either Int String
    , primsPair :: (Char, Bool)
    , primsList :: [Int]
    }

newtype Id a = Id { unId :: Text }
newtype Age = Age { unAge :: Int }

data RequestStatus
    = Approved
    | Rejected
    | Reviewing

data User = User
    { userId :: Id User
    , userName :: Text
    , userAge :: Age
    , userStatus :: RequestStatus
    }

data Guest
    = Regular Text Int
    | Visitor Text

data UserRequest = UserRequest
    { urIds :: [Id User]
    , urLimit :: Word32
    , urExample :: Maybe (Either User Guest)
    }
```

**Comment by ChShersh** [comment]
Also, after this issue is done, we can write property-based tests in Elm. If my understanding is correct, there's library like QuickCheck in Elm:

* https://package.elm-lang.org/packages/NoRedInk/elm-check/latest/

Of course we're not going to generate tests as a part of using our library. But if we have enough free time, we can test some data types that we generated for our example project.

**Comment by vrom911** [comment]
I think Elm testing of `decode . encode` property should be done! Nice idea 👍

**Comment by ChShersh** [comment]
@vrom911 I like you idea with testing nullary constructors as well, since there's additional logic for that. Maybe instead of introducing new type we can just add one more constructor to `Guest`? Like:

```haskell
data Guest
    = Regular Text Int
    | Visitor Text
    | Blocked
```
