### ISSUE TITLE
Test Elm generation on CI

### ISSUE THREAD

**Issue by chshersh** [Holmusk/elm-street#6]
They will be very useful!

**Comment by vrom911** [comment]
Or we can run `generate-elm` executable on CI and also run `elm` code?

**Comment by ChShersh** [comment]
@vrom911 That's great idea! I think we don't need golden tests for pretty printing. After thinking a little bit on this, I guess it doesn't make sense to check the formatting. We need to check that the code compiles. I like the idea of calling `generate-elm` executable on the CI and compiling elm package. We only need to figure out how to do this...
