### ISSUE TITLE
Clashing constructors

### ISSUE THREAD

**Issue by aleator** [Holmusk/elm-street#70]
If I have a Haskell type with constructor "Ok", the resulting decoder will fail to compile due to clashing with Result.Ok.

Could using qualified import help here?

**Comment by chshersh** [comment]
@aleator I think it should be possible to use a qualified name. However, I would rather rename `Ok` constructor from the Haskell side to something else. `Result` data type and its constructors are standard in the Elm ecosystem. For me personally, it would be confusing to see two different `Ok`s.

**Comment by vrom911** [comment]
Sorry for not coming back to this earlier. I have a question to understand the problem: what imports should be qualified? Do you mean imports of `Types` in `Encoder` and `Decoder` modules?

**Comment by chshersh** [comment]
I believe that adding a qualified import of a module with data types and using all generated constructors in a qualified manner will help to resolve the issue with clashing constructors. For example, here

https://github.com/Holmusk/elm-street/blob/fe762ac9748aa40d0c48ce0c964b495bb5234514/frontend/src/Core/Decoder.elm#L54

It could be `Types.Visitor` instead (or something like that).
