### ISSUE TITLE
Implement golden tests

### ISSUE THREAD

**Issue by chshersh** [Holmusk/elm-street#79]
Create `.json` file with the example of how the value of the example data type should be encoded in JSON and then:

- [ ] Parse file in Haskell and compare with golden value
- [ ] Encode golden Haskell value and compare with file
- [x] Parse file in Elm and compare with golden value
- [ ] Encode golden value in Elm and compare with the file content

**Comment by vrom911** [comment]
I will try to investigate testing on Elm side.
